load("@aspect_rules_py//py:defs.bzl", "py_binary")

py_binary(
  name = "pocket_export_html_to_csv",
  srcs = ["pocket_export_html_to_csv.py"],
)

py_binary(
  name = "youtube_playlist_to_csv",
  srcs = ["youtube_playlist_to_csv.py"],
)

