# This is a pw_console config file that defines a default window layout.
# For more info on what can be added to this file see:
#   https://pigweed.dev/pw_console/py/pw_console/docs/user_guide.html#configuration
config_title: pw_console

# Window layout
windows:
  # Left split with tabbed views.
  Split 1 tabbed:
    Python Repl:
      hidden: False
  # Right split with stacked views.
  Split 2 stacked:
    Device Logs:
      hidden: False
    Host Logs:
      hidden: False

window_column_split_method: vertical
# window_column_split_method: horizontal

# Default colors:
ui_theme: dark
code_theme: pigweed-code
swap_light_and_dark: False

# A few other choices:
# ui_theme: high-contrast-dark
# ui_theme: nord
# ui_theme: synthwave84
# code_theme: gruvbox-dark
# code_theme: pigweed-code-light
# code_theme: synthwave84

# Log display options:
spaces_between_columns: 2
hide_date_from_log_time: True
recolor_log_lines_to_match_level: False

column_order:
  # Column name
  - time
  - level
  - timestamp
  - module
  # Hidden:
  # - source_name

column_order_omit_unspecified_columns: True

snippets:
  Echo RPC:
    code: |
      device.rpcs.pw.rpc.EchoService.Echo(msg='hello world')
    description: |
      Send a string to the device and receive a response with the same
      message back.

      ```pycon
      >>> device.rpcs.pw.rpc.EchoService.Echo(msg='hello world')
      (Status.OK, pw.rpc.EchoMessage(msg='hello world'))
      ```
