version: 2
build:
  os: "ubuntu-22.04"
  tools:
    nodejs: "20"
  commands:
    - go install github.com/bazelbuild/bazelisk@latest
    - `go env GOPATH`/bin/bazelisk build //docs:docs
    - mkdir --parents $READTHEDOCS_OUTPUT/html/
    - cp --recursive bazel-bin/docs/docs_html/* $READTHEDOCS_OUTPUT/html/
