plugins:
  - name: cpp
    implementation: builtin:cpp
  - name: protoc-gen-grpc-cpp
    implementation: grpc:grpc:cpp
  - name: python
    implementation: builtin:python
  - name: pyi
    implementation: builtin:pyi
  - name: protoc-gen-grpc-python
    implementation: grpc:grpc:protoc-gen-grpc-python
rules:
  - name: proto_compile
    implementation: stackb:rules_proto:proto_compile
    visibility:
      -  //visibility:public
  - name: proto_cc_library
    implementation: stackb:rules_proto:proto_cc_library
    visibility:
      # NOTE: We're defaulting to having generated protobuf libraries public, open to changing in the future.
      -  //visibility:public
    deps:
      - "@com_google_protobuf//:protobuf"
  - name: grpc_cc_library
    implementation: stackb:rules_proto:grpc_cc_library
    visibility:
      -  //visibility:public
    deps:
      - "@com_github_grpc_grpc//:grpc++"
      - "@com_github_grpc_grpc//:grpc++_reflection"
  - name: proto_python_library
    implementation: stackb:rules_proto:proto_py_library
    visibility:
      -  //visibility:public
    deps:
      - "@com_google_protobuf//:protobuf_python"
  - name: grpc_py_library
    implementation: stackb:rules_proto:grpc_py_library
    visibility:
      -  //visibility:public
languages:
  - name: "cpp"
    plugins:
      - cpp
      - protoc-gen-grpc-cpp
    rules:
      - proto_compile
      - proto_cc_library
      # TODO(https://github.com/michael-christen/toolbox/issues/40): re-enable
      # - grpc_cc_library
  - name: "python"
    plugins:
      - python
      - pyi
      - protoc-gen-grpc-python
    rules:
      - proto_compile
      - proto_python_library
      - grpc_py_library
