[tool.isort]
# https://pycqa.github.io/isort/docs/configuration/options.html
multi_line_output = 3  # 3: vert-hanging
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 79
skip_gitignore = true
default_section = 'THIRDPARTY'
sections = ['FUTURE','STDLIB','THIRDPARTY', 'mchristen', 'FIRSTPARTY','LOCALFOLDER']
force_single_line = true
use_parentheses = true
# known_third_party

# XXX
# [tool.black]
# line-length = 79
# target-version = ['py38']
# exclude = '''
# (
#   /(
#     | \.git
#     | \.mypy_cache
#     | \.tox
#     | \.venv
#     | \bazel-*
#     | \bazel-bin
#     | \bazel-genfiles
#     | \bazel-out
#     | \bazel-testlogs
#   )/
# )
# '''
# 
# [tool.pyright]
# exclude = [
#     "bazel-*/",
# ]
