package(default_visibility = ["//visibility:public"])

filegroup(
    name = "component_images",
    srcs = glob(["*.png"]),
)

filegroup(
    name = "docs",
    srcs = [
        "sbr_components.md",
        ":component_images",
    ],
)
