load("//bzl:py.bzl", "py_binary")

py_binary(
    name = "sync_python_toolchain_versions",
    srcs = ["sync_python_toolchain_versions.py"],
    visibility = ["//:__subpackages__"],
)

package(default_visibility = ["//visibility:private"])
