
py_binary(
    name = "sphinx_build_wrapper",
    srcs = ["sphinx_build_wrapper.py"],
    deps = [
        "@pip//sphinx",
        "@pip//sphinx_rtd_theme",
    ],
    visibility = ["//visibility:public"],
)

