// Generated by PeakRDL-cheader - A free and open-source header generator
//  https://github.com/SystemRDL/PeakRDL-cheader

#ifndef LSM6DSO_SUBSET_H
#define LSM6DSO_SUBSET_H

#ifdef __cplusplus
extern "C" {
#endif
#include <stdint.h>
#include <assert.h>

// reg - lsm6dso_subset::who_am_i_r
#define LSM6DSO_SUBSET__WHO_AM_I_R__ID_bm 0xff
#define LSM6DSO_SUBSET__WHO_AM_I_R__ID_bp 0
#define LSM6DSO_SUBSET__WHO_AM_I_R__ID_bw 8
#define LSM6DSO_SUBSET__WHO_AM_I_R__ID_reset 0x6c
typedef union {
    struct __attribute__ ((__packed__)) {
        uint8_t ID :8;
    } f;
    uint8_t w;
} lsm6dso_subset__who_am_i_r_t;

// reg - lsm6dso_subset::ctrl1_xl_r
#define LSM6DSO_SUBSET__CTRL1_XL_R__RSVD0_bm 0x1
#define LSM6DSO_SUBSET__CTRL1_XL_R__RSVD0_bp 0
#define LSM6DSO_SUBSET__CTRL1_XL_R__RSVD0_bw 1
#define LSM6DSO_SUBSET__CTRL1_XL_R__RSVD0_reset 0x0
#define LSM6DSO_SUBSET__CTRL1_XL_R__LPF2_XL_EN_bm 0x2
#define LSM6DSO_SUBSET__CTRL1_XL_R__LPF2_XL_EN_bp 1
#define LSM6DSO_SUBSET__CTRL1_XL_R__LPF2_XL_EN_bw 1
#define LSM6DSO_SUBSET__CTRL1_XL_R__LPF2_XL_EN_reset 0x0
#define LSM6DSO_SUBSET__CTRL1_XL_R__FS_XL_bm 0xc
#define LSM6DSO_SUBSET__CTRL1_XL_R__FS_XL_bp 2
#define LSM6DSO_SUBSET__CTRL1_XL_R__FS_XL_bw 2
#define LSM6DSO_SUBSET__CTRL1_XL_R__FS_XL_reset 0x2
#define LSM6DSO_SUBSET__CTRL1_XL_R__ODR_XL_bm 0xf0
#define LSM6DSO_SUBSET__CTRL1_XL_R__ODR_XL_bp 4
#define LSM6DSO_SUBSET__CTRL1_XL_R__ODR_XL_bw 4
#define LSM6DSO_SUBSET__CTRL1_XL_R__ODR_XL_reset 0x4
typedef union {
    struct __attribute__ ((__packed__)) {
        uint8_t rsvd0 :1;
        uint8_t LPF2_XL_EN :1;
        uint8_t FS_XL :2;
        uint8_t ODR_XL :4;
    } f;
    uint8_t w;
} lsm6dso_subset__ctrl1_xl_r_t;

// reg - lsm6dso_subset::ctrl2_g_r
#define LSM6DSO_SUBSET__CTRL2_G_R__RSVD0_bm 0x1
#define LSM6DSO_SUBSET__CTRL2_G_R__RSVD0_bp 0
#define LSM6DSO_SUBSET__CTRL2_G_R__RSVD0_bw 1
#define LSM6DSO_SUBSET__CTRL2_G_R__RSVD0_reset 0x0
#define LSM6DSO_SUBSET__CTRL2_G_R__FS_125_bm 0x2
#define LSM6DSO_SUBSET__CTRL2_G_R__FS_125_bp 1
#define LSM6DSO_SUBSET__CTRL2_G_R__FS_125_bw 1
#define LSM6DSO_SUBSET__CTRL2_G_R__FS_125_reset 0x0
#define LSM6DSO_SUBSET__CTRL2_G_R__FS_G_bm 0xc
#define LSM6DSO_SUBSET__CTRL2_G_R__FS_G_bp 2
#define LSM6DSO_SUBSET__CTRL2_G_R__FS_G_bw 2
#define LSM6DSO_SUBSET__CTRL2_G_R__FS_G_reset 0x1
#define LSM6DSO_SUBSET__CTRL2_G_R__ODR_G_bm 0xf0
#define LSM6DSO_SUBSET__CTRL2_G_R__ODR_G_bp 4
#define LSM6DSO_SUBSET__CTRL2_G_R__ODR_G_bw 4
#define LSM6DSO_SUBSET__CTRL2_G_R__ODR_G_reset 0x4
typedef union {
    struct __attribute__ ((__packed__)) {
        uint8_t rsvd0 :1;
        uint8_t FS_125 :1;
        uint8_t FS_G :2;
        uint8_t ODR_G :4;
    } f;
    uint8_t w;
} lsm6dso_subset__ctrl2_g_r_t;

// reg - lsm6dso_subset::status_reg_r
#define LSM6DSO_SUBSET__STATUS_REG_R__XLDA_bm 0x1
#define LSM6DSO_SUBSET__STATUS_REG_R__XLDA_bp 0
#define LSM6DSO_SUBSET__STATUS_REG_R__XLDA_bw 1
#define LSM6DSO_SUBSET__STATUS_REG_R__XLDA_reset 0x0
#define LSM6DSO_SUBSET__STATUS_REG_R__GDA_bm 0x2
#define LSM6DSO_SUBSET__STATUS_REG_R__GDA_bp 1
#define LSM6DSO_SUBSET__STATUS_REG_R__GDA_bw 1
#define LSM6DSO_SUBSET__STATUS_REG_R__GDA_reset 0x0
#define LSM6DSO_SUBSET__STATUS_REG_R__TDA_bm 0x4
#define LSM6DSO_SUBSET__STATUS_REG_R__TDA_bp 2
#define LSM6DSO_SUBSET__STATUS_REG_R__TDA_bw 1
#define LSM6DSO_SUBSET__STATUS_REG_R__TDA_reset 0x0
#define LSM6DSO_SUBSET__STATUS_REG_R__RSVD_bm 0xf8
#define LSM6DSO_SUBSET__STATUS_REG_R__RSVD_bp 3
#define LSM6DSO_SUBSET__STATUS_REG_R__RSVD_bw 5
#define LSM6DSO_SUBSET__STATUS_REG_R__RSVD_reset 0x0
typedef union {
    struct __attribute__ ((__packed__)) {
        uint8_t XLDA :1;
        uint8_t GDA :1;
        uint8_t TDA :1;
        uint8_t rsvd :5;
    } f;
    uint8_t w;
} lsm6dso_subset__status_reg_r_t;

// reg - lsm6dso_subset::gyro_axis_r
#define LSM6DSO_SUBSET__GYRO_AXIS_R__DATA_bm 0xff
#define LSM6DSO_SUBSET__GYRO_AXIS_R__DATA_bp 0
#define LSM6DSO_SUBSET__GYRO_AXIS_R__DATA_bw 8
#define LSM6DSO_SUBSET__GYRO_AXIS_R__DATA_reset 0x0
typedef union {
    struct __attribute__ ((__packed__)) {
        uint8_t DATA :8;
    } f;
    uint8_t w;
} lsm6dso_subset__gyro_axis_r_t;

// reg - lsm6dso_subset::accel_axis_r
#define LSM6DSO_SUBSET__ACCEL_AXIS_R__DATA_bm 0xff
#define LSM6DSO_SUBSET__ACCEL_AXIS_R__DATA_bp 0
#define LSM6DSO_SUBSET__ACCEL_AXIS_R__DATA_bw 8
#define LSM6DSO_SUBSET__ACCEL_AXIS_R__DATA_reset 0x0
typedef union {
    struct __attribute__ ((__packed__)) {
        uint8_t DATA :8;
    } f;
    uint8_t w;
} lsm6dso_subset__accel_axis_r_t;

// addrmap - lsm6dso_subset
typedef struct __attribute__ ((__packed__)) {
    uint8_t RESERVED_0_e[0xf];
    lsm6dso_subset__who_am_i_r_t WHO_AM_I;
    lsm6dso_subset__ctrl1_xl_r_t CTRL1_XL;
    lsm6dso_subset__ctrl2_g_r_t CTRL2_G;
    uint8_t RESERVED_12_1d[0xc];
    lsm6dso_subset__status_reg_r_t STATUS_REG;
    uint8_t RESERVED_1f_21[0x3];
    lsm6dso_subset__gyro_axis_r_t OUTX_L_G;
    lsm6dso_subset__gyro_axis_r_t OUTX_H_G;
    lsm6dso_subset__gyro_axis_r_t OUTY_L_G;
    lsm6dso_subset__gyro_axis_r_t OUTY_H_G;
    lsm6dso_subset__gyro_axis_r_t OUTZ_L_G;
    lsm6dso_subset__gyro_axis_r_t OUTZ_H_G;
    lsm6dso_subset__accel_axis_r_t OUTX_L_A;
    lsm6dso_subset__accel_axis_r_t OUTX_H_A;
    lsm6dso_subset__accel_axis_r_t OUTY_L_A;
    lsm6dso_subset__accel_axis_r_t OUTY_H_A;
    lsm6dso_subset__accel_axis_r_t OUTZ_L_A;
    lsm6dso_subset__accel_axis_r_t OUTZ_H_A;
} lsm6dso_subset_t;


static_assert(sizeof(lsm6dso_subset_t) == 0x2e, "Packing error");

#ifdef __cplusplus
}
#endif

#endif /* LSM6DSO_SUBSET_H */
