load("//bzl:py.bzl", "py_library")

package(default_visibility = ["//visibility:private"])

py_library(
    name = "weighted_probability",
    srcs = ["weighted_probability.py"],
    visibility = ["//:__subpackages__"],
)
