# Generated via:
# `bazel query 'kind("py_binary", //...) + kind("py_library", //...)'`
# XXX: Resolve comments
# Finds all proto_py_library (note that if someone decided to name their python
# target similarly, we'd catch it too)
# bazel query 'attr(name, "_py_library", //...) intersect kind("py_library", //...)'
PYTHON_TARGETS = [
    "//apps:bazel_parser",
    "//bzl:pytest_main",
    "//docs:conf",
    "//examples/basic:client",
    "//examples/basic:hello_grpc_py_library",
    "//examples/basic:hello_py_library",
    "//examples/basic:main",
    "//examples/basic:server",
    "//examples/tofupilot:tofupilot_example",
    "//hw_drivers/lis3mdl:lis3mdl_py_library",
    "//hw_services/sbr:sbr_grpc_py_library",
    "//hw_services/sbr:sbr_py_library",
    "//mchristen/parsing_scripts:pocket_export_html_to_csv",
    "//mchristen/parsing_scripts:youtube_playlist_to_csv",
    "//third_party/bazel/proto:action_cache_py_library",
    "//third_party/bazel/proto:build_event_stream_py_library",
    "//third_party/bazel/proto:command_line_py_library",
    "//third_party/bazel/proto:failure_details_py_library",
    "//third_party/bazel/proto:invocation_policy_py_library",
    "//third_party/bazel/proto:option_filters_py_library",
    "//third_party/bazel/proto:package_load_metrics_py_library",
    "//third_party/bazel/proto:strategy_policy_py_library",
    "//third_party/bazel/src/main/protobuf:build_py_library",
    "//third_party/delimited_protobuf:delimited_protobuf",
    "//third_party/pigweed/tools:console",
    # "//tools:_mypy_cli",
    "//tools:bazel_utils",
    "//tools:coverage_baseline",
    "//tools:git_py_library",
    "//tools:git_utils",
    "//tools:mypy_cli",
    "//tools:utils",
    "//tools/black:black",
    "//tools/flake8:flake8",
    "//tools/ipython:ipython",
    "//tools/isort:isort",
    "//tools/jupyter:jupyter",
    "//tools/sphinx:sphinx_build_wrapper",
    "//utils:bep_reader",
    "//utils:graph_algorithms",
]
