load("//tools/sphinx:sphinx.bzl", "sphinx_html")

sphinx_html(
    name = "docs",
    config = "conf.py",
    index = "index.rst",  # Test non-canonical naming.
    srcs = [
        "hello.rst",
    ],
)
