# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: examples/basic/hello.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x65xamples/basic/hello.proto\x12\x0e\x65xamples.basic\"\x17\n\x05Hello\x12\x0e\n\x02id\x18\x01 \x01(\rR\x02id\"\"\n\x0cHelloRequest\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\"&\n\nHelloReply\x12\x18\n\x07message\x18\x01 \x01(\tR\x07message2\xfc\x01\n\x07Greeter\x12\x46\n\x08SayHello\x12\x1c.examples.basic.HelloRequest\x1a\x1a.examples.basic.HelloReply\"\x00\x12S\n\x13SayHelloStreamReply\x12\x1c.examples.basic.HelloRequest\x1a\x1a.examples.basic.HelloReply\"\x00\x30\x01\x12T\n\x12SayHelloBidiStream\x12\x1c.examples.basic.HelloRequest\x1a\x1a.examples.basic.HelloReply\"\x00(\x01\x30\x01')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'examples.basic.hello_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HELLO._serialized_start=46
  _HELLO._serialized_end=69
  _HELLOREQUEST._serialized_start=71
  _HELLOREQUEST._serialized_end=105
  _HELLOREPLY._serialized_start=107
  _HELLOREPLY._serialized_end=145
  _GREETER._serialized_start=148
  _GREETER._serialized_end=400
# @@protoc_insertion_point(module_scope)
